# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f933b58550ee85977a1c397bc14964a161c154b157698112ddf5929a72bb11fe6be91647a3cc90aac896de38aa5d505ed59e65332e2931aaaa624ecc59063c5

test:
  secret_key_base: ca16224a61a7e30a6f32ad189c5dd7e8ff7642fbd5b1b3c55ff83c4903a82f7dd0e49fd3ac2e37a6860affd380532deee1cbf20edeb49b2e2db002c64891e233

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
